version: '3.1'
services:
    php:
        build:
            context: ./
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - 8000:8000
    mysql:
        image: mysql
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: luck
